# Choreo Service Component Configuration
# Place this at the root of your GitHub repository

apiVersion: core.choreo.dev/v1beta1
kind: Component
metadata:
  name: cold-email-bot
  annotations:
    core.choreo.dev/display-name: "Cold Email Bot"
    core.choreo.dev/description: "Automated cold email outreach manager via Telegram"

spec:
  type: Service
  build:
    preset: Dockerfile
    context: .
    dockerfilePath: ./Dockerfile
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  endpoints:
    - name: api
      port: 8000
      type: REST
      networkVisibilities:
        - Public
      context: /
      schemaFilePath: ""
